[package]
name = "gil-free-python"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "gil_free_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
